image: node:9.9

pipelines:
  custom: # Pipelines that are triggered manually
    init: # -- First time init
    - step:
        script:
          - apt-get update
          - npm install
    deploy-all: # -- Deploys all files from the selected commit
    - step:
        deployment: test
        script:
          - npm install
          - npm test
          - npm run build
  branches: # Automated triggers on commits to branches
    master: # -- When committing to mast branch
    - step:
        script:
          - npm install
          - npm test
          - npm run build