image: node:9.9

pipelines:
  branches: # Automated triggers on commits to branches
    master: # -- When committing to master branch auto-deploy to production environment
    - step:
        script:
          #- export CI=false
          #- npm install
          #- npm test
          #- npm run build
          #- npm run styleguide:build
          #- mkdir build/docs
          - eval `ssh-agent`
          - ssh-add -l

          #- scp -r build/* ec2-user@fe.prod.lition.io:/var/www/html_tmp
          #- ssh ec2-user@fe.prod.lition.io "rm -r /var/www/html/*; mv /var/www/html_tmp/* /var/www/html/"
          #- ssh ec2-user@fe.prod.lition.io sudo systemctl reload httpd
    staging: # -- When committing to staging branch auto-deploy to staging environment
    - step:
        script:
          - export CI=false
          - npm install
          - npm test
          - npm run build
          - npm run styleguide:build
          - mkdir build/docs
          - scp -r build/* ec2-user@fe.staging.lition.io:/var/www/html_tmp
          - ssh ec2-user@fe.staging.lition.io "rm -r /var/www/html/*; mv /var/www/html_tmp/* /var/www/html/"
          - ssh ec2-user@fe.staging.lition.io sudo systemctl reload httpd
  custom: # Pipelines that are triggered manually
    deploy_to_production: # Deploy to production server (prod.lition.io / kundenportal.lition.de)
    - step: #Step 1: Compile
        name: Prepare build
        script:
          - export CI=false
          #- apt-get update
          - npm install
    - step: #Step 2: Do tests
        name: Do tests
        deployment: test
        script:
          - npm test
    - step: #Step 3: Compile
        name: Compile
        script:
          - npm run build
          - npm run styleguide:build
          - mkdir build/docs
          - cp -r styleguide/* build/docs
          #- scp -r build/* ec2-user@fe.staging.lition.io:/var/www/html_tmp
          #- ssh ec2-user@fe.staging.lition.io "rm -r /var/www/html/*; mv /var/www/html_tmp/* /var/www/html/"
          #- ssh ec2-user@fe.staging.lition.io sudo systemctl reload httpd
    - step: #Step 4: Deploy to staging
        name: Deploy to Production
        deployment: production
        script:
          - scp -r build/* ec2-user@fe.prod.lition.io:/var/www/html
          - ssh ec2-user@fe.prod.lition.io "rm -r /var/www/html/*; mv /var/www/html_tmp/* /var/www/html/"
          - ssh ec2-user@fe.prod.lition.io sudo systemctl reload httpd
